const express = require('express');
const router = express.Router();

const authRoutes = require('./auth');
const userRoutes = require('./users');
const vendorRoutes = require('./vendors');
const productRoutes = require('./products');
const orderRoutes = require('./orders');
const categoryRoutes = require('./categories');
const reviewRoutes = require('./reviews');
const conversationRoutes = require('./conversations');
const paymentRoutes = require('./payments');
const adminRoutes = require('./admin');
const loyaltyRoutes = require('./loyalty');
const vendorVerificationRoutes = require('./vendorVerification');
const vendorAnalyticsRoutes = require('./vendorAnalytics');
const vendorTeamRoutes = require('./vendorTeam');
const vendorSubscriptionRoutes = require('./vendorSubscription');
const vendorDashboardRoutes = require('./vendorDashboard');
const attributeRoutes = require('./attributes');
const commissionRoutes = require('./commission');
const payoutRoutes = require('./payout');
const taxRoutes = require('./tax');
const reportsRoutes = require('./reports');
const subOrderRoutes = require('./subOrder');
const shipmentRoutes = require('./shipment');
const rmaRoutes = require('./rma');
const invoiceRoutes = require('./invoice');
const couponRoutes = require('./coupon');
const ticketRoutes = require('./ticket');
const promotionRoutes = require('./promotion');
const campaignRoutes = require('./campaign');
const securityRoutes = require('./security');
const seoRoutes = require('./seo');
const taxReportRoutes = require('./taxReport');
const vendorReviewRoutes = require('./vendorReview');
const localizationRoutes = require('./localization');
const productImageRoutes = require('./productImages');
const productVariantRoutes = require('./productVariants');
const digitalAssetRoutes = require('./digitalAssets');
const bulkOperationRoutes = require('./bulkOperations');
const productQuestionRoutes = require('./productQuestion');

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/vendors/bulk-operations', bulkOperationRoutes);
router.use('/vendors', vendorRoutes);
router.use('/products', productRoutes);
router.use('/products/:id/images', productImageRoutes);
router.use('/products/:id/variants', productVariantRoutes);
router.use('/products/:id/digital-assets', digitalAssetRoutes);
router.use('/orders', orderRoutes);
router.use('/categories', categoryRoutes);
router.use('/reviews', reviewRoutes);
router.use('/conversations', conversationRoutes);
router.use('/payments', paymentRoutes);
router.use('/admin', adminRoutes);
router.use('/loyalty', loyaltyRoutes);
router.use('/vendor/verification', vendorVerificationRoutes);
router.use('/vendor/analytics', vendorAnalyticsRoutes);
router.use('/vendor/team', vendorTeamRoutes);
router.use('/vendor/subscription', vendorSubscriptionRoutes);
router.use('/vendor/dashboard', vendorDashboardRoutes);
router.use('/attributes', attributeRoutes);
router.use('/commission', commissionRoutes);
router.use('/payouts', payoutRoutes);
router.use('/tax', taxRoutes);
router.use('/reports', reportsRoutes);

// New operational routes
router.use('/', subOrderRoutes);
router.use('/', shipmentRoutes);
router.use('/', rmaRoutes);
router.use('/', invoiceRoutes);
router.use('/', couponRoutes);
router.use('/', ticketRoutes);
router.use('/', promotionRoutes);
router.use('/', campaignRoutes);
router.use('/', securityRoutes);
router.use('/seo', seoRoutes);
router.use('/localization', localizationRoutes);
router.use('/', taxReportRoutes);
router.use('/', vendorReviewRoutes);
router.use('/', productQuestionRoutes);

module.exports = router;
