import { useState, useEffect } from 'react';
import api from '../../services/api';
import toast from 'react-hot-toast';

const SeoManager = () => {
  const [activeTab, setActiveTab] = useState('audit');
  const [audit, setAudit] = useState([]);
  const [metas, setMetas] = useState([]);
  const [loading, setLoading] = useState(true);
  const [pagination, setPagination] = useState({ page: 1, limit: 20, total: 0, pages: 0 });
  const [filters, setFilters] = useState({
    entityType: '',
    hasIssues: '',
    isAutoGenerated: '',
    search: '',
  });
  const [selectedMeta, setSelectedMeta] = useState(null);
  const [sitemapStats, setSitemapStats] = useState(null);

  useEffect(() => {
    if (activeTab === 'audit') {
      fetchAudit();
    } else if (activeTab === 'metas') {
      fetchMetas();
    } else if (activeTab === 'sitemap') {
      fetchSitemapStats();
    }
  }, [activeTab, pagination.page, filters]);

  const fetchAudit = async () => {
    try {
      setLoading(true);
      const response = await api.get('/seo/admin/audit');
      setAudit(response.data.data);
    } catch (error) {
      console.error('Failed to fetch audit:', error);
      toast.error('Failed to fetch SEO audit');
    } finally {
      setLoading(false);
    }
  };

  const fetchMetas = async () => {
    try {
      setLoading(true);
      const params = new URLSearchParams({
        page: pagination.page,
        limit: pagination.limit,
      });

      Object.entries(filters).forEach(([key, value]) => {
        if (value) params.append(key, value);
      });

      const response = await api.get(`/seo/admin/metas?${params}`);
      setMetas(response.data.data);
      setPagination(prev => ({
        ...prev,
        ...response.data.pagination,
      }));
    } catch (error) {
      console.error('Failed to fetch metas:', error);
      toast.error('Failed to fetch SEO metas');
    } finally {
      setLoading(false);
    }
  };

  const fetchSitemapStats = async () => {
    try {
      setLoading(true);
      const response = await api.get('/seo/admin/sitemap/stats');
      setSitemapStats(response.data.data);
    } catch (error) {
      console.error('Failed to fetch sitemap stats:', error);
      toast.error('Failed to fetch sitemap stats');
    } finally {
      setLoading(false);
    }
  };

  const recalculateScores = async () => {
    try {
      await api.post('/seo/admin/recalculate-scores', {});
      fetchAudit();
      toast.success('SEO scores recalculated successfully');
    } catch (error) {
      console.error('Failed to recalculate scores:', error);
      toast.error('Failed to recalculate scores');
    }
  };

  const regenerateSitemap = async () => {
    try {
      await api.post('/seo/admin/sitemap/generate');
      toast.success('Sitemap generation started');
      setTimeout(fetchSitemapStats, 5000);
    } catch (error) {
      console.error('Failed to regenerate sitemap:', error);
      toast.error('Failed to regenerate sitemap');
    }
  };

  const getAvatarColor = (index) => {
    const colors = [
      'bg-emerald-500', 'bg-blue-500', 'bg-purple-500', 'bg-pink-500',
      'bg-orange-500', 'bg-teal-500', 'bg-indigo-500', 'bg-rose-500'
    ];
    return colors[index % colors.length];
  };

  const getSeoScoreColor = (score) => {
    if (score >= 80) return 'text-emerald-600';
    if (score >= 60) return 'text-yellow-600';
    if (score >= 40) return 'text-orange-600';
    return 'text-red-600';
  };

  const getSeoScoreBg = (score) => {
    if (score >= 80) return 'bg-emerald-100 text-emerald-700';
    if (score >= 60) return 'bg-yellow-100 text-yellow-700';
    if (score >= 40) return 'bg-orange-100 text-orange-700';
    return 'bg-red-100 text-red-700';
  };

  // Icons
  const ChartIcon = () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
    </svg>
  );

  const DocumentIcon = () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
    </svg>
  );

  const GlobeIcon = () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  );

  const RefreshIcon = () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
    </svg>
  );

  const SearchIcon = () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
    </svg>
  );

  const LinkIcon = () => (
    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />
    </svg>
  );

  const CheckCircleIcon = () => (
    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  );

  const ExclamationIcon = () => (
    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
    </svg>
  );

  const CalendarIcon = () => (
    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
    </svg>
  );

  const tabs = [
    { id: 'audit', label: 'SEO Audit', icon: ChartIcon },
    { id: 'metas', label: 'SEO Metas', icon: DocumentIcon },
    { id: 'sitemap', label: 'Sitemap', icon: GlobeIcon },
  ];

  // Calculate audit stats
  const auditStats = {
    totalItems: audit.reduce((sum, item) => sum + (item.total || 0), 0),
    avgScore: audit.length > 0 ? Math.round(audit.reduce((sum, item) => sum + (item.avgScore || 0), 0) / audit.length) : 0,
    missingMeta: audit.reduce((sum, item) => sum + (item.missingTitle || 0) + (item.missingDescription || 0), 0),
    customized: audit.reduce((sum, item) => sum + (item.customized || 0), 0),
  };

  return (
    <div className="py-4 px-3 sm:p-6 bg-gray-50 min-h-screen">
      {/* Header */}
      <div className="flex items-center justify-between gap-2 mb-3 sm:mb-6">
        <div>
          <h1 className="text-lg sm:text-2xl font-bold text-emerald-600">SEO Manager</h1>
          <p className="text-gray-500 text-[10px] sm:text-sm mt-0.5">Optimize your site's search engine visibility</p>
        </div>
        <div className="flex gap-1.5 sm:gap-2">
          <button
            onClick={recalculateScores}
            className="px-2 py-1.5 sm:px-4 sm:py-2 bg-white border border-gray-200 text-gray-700 rounded-lg sm:rounded-xl hover:bg-gray-50 transition-colors flex items-center gap-1 sm:gap-2 text-[10px] sm:text-sm font-medium"
          >
            <RefreshIcon />
            <span className="hidden sm:inline">Recalculate Scores</span>
            <span className="sm:hidden">Recalculate</span>
          </button>
          <button
            onClick={regenerateSitemap}
            className="px-2 py-1.5 sm:px-4 sm:py-2 bg-emerald-500 text-white rounded-lg sm:rounded-xl hover:bg-emerald-600 transition-colors flex items-center gap-1 sm:gap-2 text-[10px] sm:text-sm font-medium"
          >
            <GlobeIcon />
            <span className="hidden sm:inline">Regenerate Sitemap</span>
            <span className="sm:hidden">Sitemap</span>
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="bg-white rounded-xl sm:rounded-2xl shadow-sm mb-3 sm:mb-6">
        <div className="flex border-b border-gray-100">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex-1 sm:flex-none flex items-center justify-center sm:justify-start gap-1.5 sm:gap-2 px-3 py-2.5 sm:px-6 sm:py-4 font-medium text-xs sm:text-sm transition-colors relative ${
                activeTab === tab.id
                  ? 'text-emerald-600'
                  : 'text-gray-500 hover:text-gray-700'
              }`}
            >
              <tab.icon />
              {tab.label}
              {activeTab === tab.id && (
                <span className="absolute bottom-0 left-0 right-0 h-0.5 bg-emerald-500"></span>
              )}
            </button>
          ))}
        </div>
      </div>

      {/* Audit Tab */}
      {activeTab === 'audit' && (
        <div>
          {/* Stats Cards */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-2 sm:gap-4 mb-3 sm:mb-6">
            <div className="bg-white rounded-xl sm:rounded-2xl shadow-sm p-3 sm:p-5">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-[10px] sm:text-sm text-gray-500 font-medium">Total Items</p>
                  <p className="text-lg sm:text-2xl font-bold text-gray-900 mt-0.5 sm:mt-1">{auditStats.totalItems}</p>
                </div>
                <div className="w-9 h-9 sm:w-12 sm:h-12 bg-emerald-100 rounded-lg sm:rounded-xl flex items-center justify-center text-emerald-600 shrink-0">
                  <LinkIcon />
                </div>
              </div>
            </div>

            <div className="bg-white rounded-xl sm:rounded-2xl shadow-sm p-3 sm:p-5">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-[10px] sm:text-sm text-gray-500 font-medium">Avg Score</p>
                  <p className={`text-lg sm:text-2xl font-bold mt-0.5 sm:mt-1 ${getSeoScoreColor(auditStats.avgScore)}`}>
                    {auditStats.avgScore}%
                  </p>
                </div>
                <div className="w-9 h-9 sm:w-12 sm:h-12 bg-blue-100 rounded-lg sm:rounded-xl flex items-center justify-center text-blue-600 shrink-0">
                  <ChartIcon />
                </div>
              </div>
            </div>

            <div className="bg-white rounded-xl sm:rounded-2xl shadow-sm p-3 sm:p-5">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-[10px] sm:text-sm text-gray-500 font-medium">Missing Meta</p>
                  <p className="text-lg sm:text-2xl font-bold text-gray-900 mt-0.5 sm:mt-1">{auditStats.missingMeta}</p>
                </div>
                <div className="w-9 h-9 sm:w-12 sm:h-12 bg-orange-100 rounded-lg sm:rounded-xl flex items-center justify-center text-orange-600 shrink-0">
                  <ExclamationIcon />
                </div>
              </div>
            </div>

            <div className="bg-white rounded-xl sm:rounded-2xl shadow-sm p-3 sm:p-5">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-[10px] sm:text-sm text-gray-500 font-medium">Customized</p>
                  <p className="text-lg sm:text-2xl font-bold text-gray-900 mt-0.5 sm:mt-1">{auditStats.customized}</p>
                </div>
                <div className="w-9 h-9 sm:w-12 sm:h-12 bg-purple-100 rounded-lg sm:rounded-xl flex items-center justify-center text-purple-600 shrink-0">
                  <CheckCircleIcon />
                </div>
              </div>
            </div>
          </div>

          {/* Audit Cards */}
          {loading ? (
            <div className="flex justify-center py-6 sm:py-12">
              <div className="w-8 h-8 sm:w-10 sm:h-10 border-4 border-emerald-200 border-t-emerald-600 rounded-full animate-spin"></div>
            </div>
          ) : (
            <div className="grid grid-cols-2 md:grid-cols-2 lg:grid-cols-4 gap-2 sm:gap-4">
              {audit.map((item, index) => (
                <div key={item.entityType} className="bg-white rounded-xl sm:rounded-2xl shadow-sm p-3 sm:p-5">
                  <div className="flex items-center gap-2 sm:gap-3 mb-2 sm:mb-4">
                    <div className={`w-7 h-7 sm:w-10 sm:h-10 ${getAvatarColor(index)} rounded-lg sm:rounded-xl flex items-center justify-center text-white text-xs sm:text-base font-semibold shrink-0`}>
                      {item.entityType[0].toUpperCase()}
                    </div>
                    <h3 className="text-xs sm:text-base font-semibold text-gray-900 capitalize">{item.entityType}s</h3>
                  </div>

                  <div className="space-y-1.5 sm:space-y-3">
                    <div className="flex justify-between items-center">
                      <span className="text-[10px] sm:text-sm text-gray-500">Total</span>
                      <span className="text-[10px] sm:text-sm font-semibold text-gray-900">{item.total}</span>
                    </div>
                    <div className="flex justify-between items-center">
                      <span className="text-[10px] sm:text-sm text-gray-500">Avg Score</span>
                      <span className={`text-[10px] sm:text-sm font-semibold px-1.5 sm:px-2 py-0.5 rounded-lg ${getSeoScoreBg(item.avgScore)}`}>
                        {item.avgScore || 0}%
                      </span>
                    </div>
                    <div className="flex justify-between items-center">
                      <span className="text-[10px] sm:text-sm text-gray-500">No Title</span>
                      <span className={`text-[10px] sm:text-sm font-semibold ${item.missingTitle > 0 ? 'text-red-600' : 'text-emerald-600'}`}>
                        {item.missingTitle}
                      </span>
                    </div>
                    <div className="flex justify-between items-center">
                      <span className="text-[10px] sm:text-sm text-gray-500">No Desc</span>
                      <span className={`text-[10px] sm:text-sm font-semibold ${item.missingDescription > 0 ? 'text-red-600' : 'text-emerald-600'}`}>
                        {item.missingDescription}
                      </span>
                    </div>
                    <div className="flex justify-between items-center">
                      <span className="text-[10px] sm:text-sm text-gray-500">No OG Img</span>
                      <span className={`text-[10px] sm:text-sm font-semibold ${item.missingOgImage > 0 ? 'text-orange-600' : 'text-emerald-600'}`}>
                        {item.missingOgImage}
                      </span>
                    </div>
                    <div className="pt-1.5 sm:pt-2 border-t border-gray-100 flex justify-between items-center">
                      <span className="text-[10px] sm:text-sm text-gray-500">Custom</span>
                      <span className="text-[10px] sm:text-sm font-semibold text-emerald-600">{item.customized}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Metas Tab */}
      {activeTab === 'metas' && (
        <div>
          {/* Filters */}
          <div className="bg-white rounded-xl sm:rounded-2xl shadow-sm p-3 sm:p-5 mb-3 sm:mb-6">
            <div className="grid grid-cols-2 md:grid-cols-5 gap-2 sm:gap-4">
              <div>
                <label className="block text-[10px] sm:text-sm font-medium text-gray-700 mb-0.5 sm:mb-1">Entity Type</label>
                <select
                  className="w-full px-2 py-1.5 sm:px-3 sm:py-2 border border-gray-200 rounded-lg sm:rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent text-xs sm:text-sm"
                  value={filters.entityType}
                  onChange={(e) => setFilters(prev => ({ ...prev, entityType: e.target.value }))}
                >
                  <option value="">All Types</option>
                  <option value="product">Products</option>
                  <option value="category">Categories</option>
                  <option value="vendor">Vendors</option>
                  <option value="page">Pages</option>
                </select>
              </div>
              <div>
                <label className="block text-[10px] sm:text-sm font-medium text-gray-700 mb-0.5 sm:mb-1">Has Issues</label>
                <select
                  className="w-full px-2 py-1.5 sm:px-3 sm:py-2 border border-gray-200 rounded-lg sm:rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent text-xs sm:text-sm"
                  value={filters.hasIssues}
                  onChange={(e) => setFilters(prev => ({ ...prev, hasIssues: e.target.value }))}
                >
                  <option value="">All</option>
                  <option value="true">With Issues</option>
                </select>
              </div>
              <div>
                <label className="block text-[10px] sm:text-sm font-medium text-gray-700 mb-0.5 sm:mb-1">Generation</label>
                <select
                  className="w-full px-2 py-1.5 sm:px-3 sm:py-2 border border-gray-200 rounded-lg sm:rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent text-xs sm:text-sm"
                  value={filters.isAutoGenerated}
                  onChange={(e) => setFilters(prev => ({ ...prev, isAutoGenerated: e.target.value }))}
                >
                  <option value="">All</option>
                  <option value="true">Auto</option>
                  <option value="false">Custom</option>
                </select>
              </div>
              <div>
                <label className="block text-[10px] sm:text-sm font-medium text-gray-700 mb-0.5 sm:mb-1">Search</label>
                <div className="relative">
                  <input
                    type="text"
                    className="w-full pl-7 sm:pl-10 pr-2 sm:pr-3 py-1.5 sm:py-2 border border-gray-200 rounded-lg sm:rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent text-xs sm:text-sm"
                    placeholder="Search slug or title..."
                    value={filters.search}
                    onChange={(e) => setFilters(prev => ({ ...prev, search: e.target.value }))}
                  />
                  <div className="absolute left-2 sm:left-3 top-1/2 -translate-y-1/2 text-gray-400">
                    <svg className="w-3.5 h-3.5 sm:w-5 sm:h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                    </svg>
                  </div>
                </div>
              </div>
              <div className="flex items-end col-span-2 sm:col-span-1">
                <button
                  onClick={() => setFilters({ entityType: '', hasIssues: '', isAutoGenerated: '', search: '' })}
                  className="w-full px-3 py-1.5 sm:px-4 sm:py-2 bg-gray-100 text-gray-700 rounded-lg sm:rounded-xl hover:bg-gray-200 transition-colors text-xs sm:text-sm font-medium"
                >
                  Clear Filters
                </button>
              </div>
            </div>
          </div>

          {/* Metas Table */}
          <div className="bg-white rounded-xl sm:rounded-2xl shadow-sm overflow-hidden">
            {/* Desktop Table */}
            <div className="hidden sm:block overflow-x-auto">
              <table className="w-full">
                <thead className="bg-emerald-50">
                  <tr>
                    <th className="px-5 py-4 text-left text-xs font-semibold text-emerald-700 uppercase tracking-wider">Slug</th>
                    <th className="px-5 py-4 text-left text-xs font-semibold text-emerald-700 uppercase tracking-wider">Type</th>
                    <th className="px-5 py-4 text-left text-xs font-semibold text-emerald-700 uppercase tracking-wider">Meta Title</th>
                    <th className="px-5 py-4 text-left text-xs font-semibold text-emerald-700 uppercase tracking-wider">Score</th>
                    <th className="px-5 py-4 text-left text-xs font-semibold text-emerald-700 uppercase tracking-wider">Issues</th>
                    <th className="px-5 py-4 text-left text-xs font-semibold text-emerald-700 uppercase tracking-wider">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {loading ? (
                    <tr>
                      <td colSpan={6} className="px-5 py-12 text-center">
                        <div className="w-10 h-10 border-4 border-emerald-200 border-t-emerald-600 rounded-full animate-spin mx-auto"></div>
                      </td>
                    </tr>
                  ) : metas.length === 0 ? (
                    <tr>
                      <td colSpan={6} className="px-5 py-12 text-center">
                        <div className="w-16 h-16 bg-emerald-100 rounded-2xl flex items-center justify-center mx-auto mb-3 text-emerald-600">
                          <DocumentIcon />
                        </div>
                        <p className="text-gray-500 font-medium">No SEO metas found</p>
                        <p className="text-sm text-gray-400 mt-1">Try adjusting your filters</p>
                      </td>
                    </tr>
                  ) : (
                    metas.map((meta, index) => (
                      <tr key={meta._id} className="hover:bg-gray-50 transition-colors">
                        <td className="px-5 py-4">
                          <div className="flex items-center gap-3">
                            <div className={`w-8 h-8 ${getAvatarColor(index)} rounded-lg flex items-center justify-center text-white text-xs font-semibold`}>
                              {meta.slug[0].toUpperCase()}
                            </div>
                            <code className="text-sm bg-gray-100 px-2 py-1 rounded-lg text-gray-700">
                              /{meta.slug.substring(0, 30)}{meta.slug.length > 30 ? '...' : ''}
                            </code>
                          </div>
                        </td>
                        <td className="px-5 py-4">
                          <span className="px-2.5 py-1 text-xs rounded-lg bg-gray-100 text-gray-700 font-medium capitalize">
                            {meta.entityType}
                          </span>
                        </td>
                        <td className="px-5 py-4 text-sm text-gray-900 max-w-xs truncate">
                          {meta.metaTitle || <span className="text-red-500 font-medium">Missing</span>}
                        </td>
                        <td className="px-5 py-4">
                          <span className={`px-2.5 py-1 text-xs rounded-lg font-semibold ${getSeoScoreBg(meta.seoScore)}`}>
                            {meta.seoScore || 0}%
                          </span>
                        </td>
                        <td className="px-5 py-4">
                          {meta.seoIssues?.length > 0 ? (
                            <span className="text-orange-600 text-sm font-medium">
                              {meta.seoIssues.length} issues
                            </span>
                          ) : (
                            <span className="text-emerald-600 text-sm font-medium">None</span>
                          )}
                        </td>
                        <td className="px-5 py-4">
                          <button
                            onClick={() => setSelectedMeta(meta)}
                            className="px-3 py-1.5 bg-emerald-50 text-emerald-600 rounded-lg hover:bg-emerald-100 transition-colors text-sm font-medium"
                          >
                            Edit
                          </button>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>

            {/* Mobile Card View */}
            <div className="sm:hidden">
              {/* Mobile Header */}
              <div className="grid grid-cols-12 gap-1 bg-emerald-50 px-3 py-2">
                <span className="col-span-4 text-[9px] font-semibold text-emerald-700 uppercase">Slug</span>
                <span className="col-span-2 text-[9px] font-semibold text-emerald-700 uppercase">Type</span>
                <span className="col-span-2 text-[9px] font-semibold text-emerald-700 uppercase">Score</span>
                <span className="col-span-2 text-[9px] font-semibold text-emerald-700 uppercase">Issues</span>
                <span className="col-span-2 text-[9px] font-semibold text-emerald-700 uppercase text-right">Action</span>
              </div>
              {loading ? (
                <div className="py-6 text-center">
                  <div className="w-8 h-8 border-4 border-emerald-200 border-t-emerald-600 rounded-full animate-spin mx-auto"></div>
                </div>
              ) : metas.length === 0 ? (
                <div className="py-6 text-center">
                  <DocumentIcon />
                  <p className="text-xs text-gray-500 mt-1">No SEO metas found</p>
                  <p className="text-[10px] text-gray-400">Try adjusting your filters</p>
                </div>
              ) : (
                <div className="divide-y divide-gray-100">
                  {metas.map((meta, index) => (
                    <div key={meta._id} className="grid grid-cols-12 gap-1 items-center px-3 py-2">
                      <div className="col-span-4 flex items-center gap-1.5 min-w-0">
                        <div className={`w-5 h-5 ${getAvatarColor(index)} rounded flex items-center justify-center text-white text-[8px] font-bold shrink-0`}>
                          {meta.slug[0].toUpperCase()}
                        </div>
                        <code className="text-[10px] text-gray-700 truncate">/{meta.slug.substring(0, 12)}</code>
                      </div>
                      <div className="col-span-2">
                        <span className="px-1 py-0.5 text-[9px] rounded bg-gray-100 text-gray-700 font-medium capitalize">
                          {meta.entityType}
                        </span>
                      </div>
                      <div className="col-span-2">
                        <span className={`px-1 py-0.5 text-[9px] rounded font-semibold ${getSeoScoreBg(meta.seoScore)}`}>
                          {meta.seoScore || 0}%
                        </span>
                      </div>
                      <div className="col-span-2">
                        {meta.seoIssues?.length > 0 ? (
                          <span className="text-[10px] text-orange-600 font-medium">{meta.seoIssues.length}</span>
                        ) : (
                          <span className="text-[10px] text-emerald-600 font-medium">None</span>
                        )}
                      </div>
                      <div className="col-span-2 text-right">
                        <button
                          onClick={() => setSelectedMeta(meta)}
                          className="px-1.5 py-0.5 bg-emerald-50 text-emerald-600 rounded text-[10px] font-medium"
                        >
                          Edit
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Pagination */}
            {pagination.pages > 1 && (
              <div className="px-3 py-2 sm:px-5 sm:py-4 border-t border-gray-100 flex justify-between items-center gap-2">
                <span className="text-[10px] sm:text-sm text-gray-500">
                  {metas.length}/{pagination.total}
                </span>
                <div className="flex gap-1 sm:gap-2">
                  <button
                    onClick={() => setPagination(prev => ({ ...prev, page: prev.page - 1 }))}
                    disabled={pagination.page === 1}
                    className="px-2 py-1 sm:px-4 sm:py-2 bg-white border border-gray-200 text-gray-700 rounded-lg sm:rounded-xl hover:bg-gray-50 transition-colors text-[10px] sm:text-sm font-medium disabled:opacity-50"
                  >
                    Prev
                  </button>
                  <span className="px-2 py-1 sm:px-4 sm:py-2 text-[10px] sm:text-sm text-gray-600">
                    {pagination.page}/{pagination.pages}
                  </span>
                  <button
                    onClick={() => setPagination(prev => ({ ...prev, page: prev.page + 1 }))}
                    disabled={pagination.page === pagination.pages}
                    className="px-2 py-1 sm:px-4 sm:py-2 bg-white border border-gray-200 text-gray-700 rounded-lg sm:rounded-xl hover:bg-gray-50 transition-colors text-[10px] sm:text-sm font-medium disabled:opacity-50"
                  >
                    Next
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Sitemap Tab */}
      {activeTab === 'sitemap' && (
        <div>
          {loading ? (
            <div className="flex justify-center py-12">
              <div className="w-10 h-10 border-4 border-emerald-200 border-t-emerald-600 rounded-full animate-spin"></div>
            </div>
          ) : sitemapStats ? (
            <div>
              {/* Overview Stats */}
              <div className="grid grid-cols-3 gap-2 sm:gap-4 mb-3 sm:mb-6">
                <div className="bg-white rounded-xl sm:rounded-2xl shadow-sm p-3 sm:p-5">
                  <div className="flex flex-col sm:flex-row items-start sm:items-center sm:justify-between gap-1 sm:gap-0">
                    <div>
                      <p className="text-[10px] sm:text-sm text-gray-500 font-medium">Total URLs</p>
                      <p className="text-sm sm:text-2xl font-bold text-gray-900 mt-0.5">{sitemapStats.totalUrls?.toLocaleString()}</p>
                    </div>
                    <div className="hidden sm:flex w-12 h-12 bg-emerald-100 rounded-xl items-center justify-center text-emerald-600 shrink-0">
                      <LinkIcon />
                    </div>
                  </div>
                </div>
                <div className="bg-white rounded-xl sm:rounded-2xl shadow-sm p-3 sm:p-5">
                  <div className="flex flex-col sm:flex-row items-start sm:items-center sm:justify-between gap-1 sm:gap-0">
                    <div>
                      <p className="text-[10px] sm:text-sm text-gray-500 font-medium">Size</p>
                      <p className="text-sm sm:text-2xl font-bold text-gray-900 mt-0.5">{sitemapStats.totalSizeFormatted}</p>
                    </div>
                    <div className="hidden sm:flex w-12 h-12 bg-blue-100 rounded-xl items-center justify-center text-blue-600 shrink-0">
                      <DocumentIcon />
                    </div>
                  </div>
                </div>
                <div className="bg-white rounded-xl sm:rounded-2xl shadow-sm p-3 sm:p-5">
                  <div className="flex flex-col sm:flex-row items-start sm:items-center sm:justify-between gap-1 sm:gap-0">
                    <div>
                      <p className="text-[10px] sm:text-sm text-gray-500 font-medium">Generated</p>
                      <p className="text-sm sm:text-2xl font-bold text-gray-900 mt-0.5">
                        {sitemapStats.lastGenerated
                          ? new Date(sitemapStats.lastGenerated).toLocaleDateString()
                          : 'Never'}
                      </p>
                    </div>
                    <div className="hidden sm:flex w-12 h-12 bg-purple-100 rounded-xl items-center justify-center text-purple-600 shrink-0">
                      <CalendarIcon />
                    </div>
                  </div>
                </div>
              </div>

              {/* Sitemap Configurations */}
              <div className="bg-white rounded-xl sm:rounded-2xl shadow-sm">
                <div className="px-3 py-2 sm:p-5 border-b border-gray-100">
                  <h2 className="text-sm sm:text-lg font-semibold text-gray-900">Sitemap Configuration</h2>
                </div>
                <div className="divide-y divide-gray-100">
                  {sitemapStats.configs?.map((config, index) => (
                    <div key={config.entityType} className="px-3 py-2.5 sm:p-5 flex items-center justify-between hover:bg-gray-50 transition-colors">
                      <div className="flex items-center gap-2 sm:gap-4">
                        <div className={`w-7 h-7 sm:w-10 sm:h-10 ${getAvatarColor(index)} rounded-lg sm:rounded-xl flex items-center justify-center text-white text-xs sm:text-base font-semibold shrink-0`}>
                          {config.entityType[0].toUpperCase()}
                        </div>
                        <div>
                          <p className="text-xs sm:text-base font-medium text-gray-900 capitalize">{config.entityType}</p>
                          <p className="text-[10px] sm:text-sm text-gray-500">
                            {config.urlCount?.toLocaleString()} URLs
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-2 sm:gap-4">
                        {config.hasError && (
                          <span className="text-red-600 text-[10px] sm:text-sm font-medium bg-red-50 px-2 py-0.5 sm:px-3 sm:py-1 rounded-lg">
                            Error
                          </span>
                        )}
                        <span className={`px-2 py-1 sm:px-3 sm:py-1.5 text-[10px] sm:text-xs rounded-lg font-semibold ${
                          config.isEnabled
                            ? 'bg-emerald-100 text-emerald-700'
                            : 'bg-gray-100 text-gray-600'
                        }`}>
                          {config.isEnabled ? 'Enabled' : 'Disabled'}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-white rounded-2xl shadow-sm p-12 text-center">
              <div className="w-16 h-16 bg-emerald-100 rounded-2xl flex items-center justify-center mx-auto mb-4 text-emerald-600">
                <GlobeIcon />
              </div>
              <p className="text-gray-500 font-medium">No sitemap stats available</p>
              <p className="text-sm text-gray-400 mt-1">Generate a sitemap to see statistics</p>
            </div>
          )}
        </div>
      )}

      {/* Edit Modal */}
      {selectedMeta && (
        <SeoEditModal
          meta={selectedMeta}
          onClose={() => setSelectedMeta(null)}
          onSave={() => {
            setSelectedMeta(null);
            fetchMetas();
          }}
        />
      )}
    </div>
  );
};

// SEO Edit Modal Component
const SeoEditModal = ({ meta, onClose, onSave }) => {
  const [form, setForm] = useState({
    metaTitle: meta.metaTitle || '',
    metaDescription: meta.metaDescription || '',
    metaKeywords: meta.metaKeywords?.join(', ') || '',
    ogTitle: meta.ogTitle || '',
    ogDescription: meta.ogDescription || '',
    ogImage: meta.ogImage || '',
    robotsDirective: meta.robotsDirective || 'index,follow',
    sitemapPriority: meta.sitemapPriority || 0.5,
    excludeFromSitemap: meta.excludeFromSitemap || false,
  });
  const [saving, setSaving] = useState(false);

  const handleSave = async () => {
    try {
      setSaving(true);
      await api.put(`/seo/${meta.entityType}/${meta.entityId}`, {
        ...form,
        metaKeywords: form.metaKeywords.split(',').map(k => k.trim()).filter(Boolean),
      });
      toast.success('SEO meta saved successfully');
      onSave();
    } catch (error) {
      console.error('Failed to save SEO:', error);
      toast.error(error.response?.data?.message || 'Failed to save');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-5 border-b border-gray-100 flex justify-between items-center sticky top-0 bg-white z-10">
          <h2 className="text-lg font-semibold text-gray-900">Edit SEO Meta</h2>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-xl transition-colors">
            <svg className="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div className="p-5 space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Slug</label>
            <code className="block bg-gray-100 px-4 py-2.5 rounded-xl text-sm text-gray-700">/{meta.slug}</code>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Meta Title <span className="text-gray-400">({form.metaTitle.length}/70)</span>
            </label>
            <input
              type="text"
              className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent text-sm"
              maxLength={70}
              value={form.metaTitle}
              onChange={(e) => setForm(prev => ({ ...prev, metaTitle: e.target.value }))}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Meta Description <span className="text-gray-400">({form.metaDescription.length}/160)</span>
            </label>
            <textarea
              className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent text-sm"
              rows={3}
              maxLength={160}
              value={form.metaDescription}
              onChange={(e) => setForm(prev => ({ ...prev, metaDescription: e.target.value }))}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Meta Keywords (comma-separated)</label>
            <input
              type="text"
              className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent text-sm"
              value={form.metaKeywords}
              onChange={(e) => setForm(prev => ({ ...prev, metaKeywords: e.target.value }))}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">OG Title</label>
            <input
              type="text"
              className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent text-sm"
              maxLength={95}
              value={form.ogTitle}
              onChange={(e) => setForm(prev => ({ ...prev, ogTitle: e.target.value }))}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">OG Description</label>
            <textarea
              className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent text-sm"
              rows={2}
              maxLength={200}
              value={form.ogDescription}
              onChange={(e) => setForm(prev => ({ ...prev, ogDescription: e.target.value }))}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">OG Image URL</label>
            <input
              type="url"
              className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent text-sm"
              value={form.ogImage}
              onChange={(e) => setForm(prev => ({ ...prev, ogImage: e.target.value }))}
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Robots Directive</label>
              <select
                className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent text-sm"
                value={form.robotsDirective}
                onChange={(e) => setForm(prev => ({ ...prev, robotsDirective: e.target.value }))}
              >
                <option value="index,follow">Index, Follow</option>
                <option value="noindex,follow">No Index, Follow</option>
                <option value="index,nofollow">Index, No Follow</option>
                <option value="noindex,nofollow">No Index, No Follow</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Sitemap Priority (0-1)</label>
              <input
                type="number"
                className="w-full px-4 py-2.5 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent text-sm"
                min={0}
                max={1}
                step={0.1}
                value={form.sitemapPriority}
                onChange={(e) => setForm(prev => ({ ...prev, sitemapPriority: parseFloat(e.target.value) }))}
              />
            </div>
          </div>

          <div>
            <label className="flex items-center gap-3 cursor-pointer">
              <input
                type="checkbox"
                className="w-5 h-5 rounded-lg border-gray-300 text-emerald-600 focus:ring-emerald-500"
                checked={form.excludeFromSitemap}
                onChange={(e) => setForm(prev => ({ ...prev, excludeFromSitemap: e.target.checked }))}
              />
              <span className="text-sm text-gray-700">Exclude from sitemap</span>
            </label>
          </div>

          {/* Issues */}
          {meta.seoIssues?.length > 0 && (
            <div className="bg-yellow-50 border border-yellow-200 rounded-xl p-4">
              <h4 className="font-semibold text-yellow-800 mb-2">SEO Issues</h4>
              <ul className="space-y-2">
                {meta.seoIssues.map((issue, idx) => (
                  <li key={idx} className="text-sm text-yellow-700 flex items-center gap-2">
                    <span className={`w-2 h-2 rounded-full flex-shrink-0 ${
                      issue.severity === 'error' ? 'bg-red-500' :
                      issue.severity === 'warning' ? 'bg-yellow-500' : 'bg-blue-500'
                    }`}></span>
                    {issue.message}
                  </li>
                ))}
              </ul>
            </div>
          )}

          <div className="flex justify-end gap-3 pt-4 border-t border-gray-100">
            <button
              onClick={onClose}
              className="px-4 py-2.5 bg-gray-100 text-gray-700 rounded-xl hover:bg-gray-200 transition-colors text-sm font-medium"
            >
              Cancel
            </button>
            <button
              onClick={handleSave}
              disabled={saving}
              className="px-4 py-2.5 bg-emerald-500 text-white rounded-xl hover:bg-emerald-600 transition-colors text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {saving ? 'Saving...' : 'Save Changes'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SeoManager;
