const mongoose = require('mongoose');

const rmaMessageSchema = new mongoose.Schema(
  {
    rmaRequest: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'RMARequest',
      required: true,
    },
    sender: {
      type: {
        type: String,
        enum: ['customer', 'vendor', 'admin', 'system'],
        required: true,
      },
      user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
      },
      name: { type: String }, // For display purposes
    },
    message: {
      type: String,
      required: true,
    },
    attachments: [
      {
        filename: { type: String },
        url: { type: String },
        mimeType: { type: String },
        size: { type: Number },
      },
    ],
    isInternal: {
      type: Boolean,
      default: false, // If true, only visible to admin
    },
    isAutoGenerated: {
      type: Boolean,
      default: false, // System-generated messages
    },
    readBy: [
      {
        user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
        readAt: { type: Date },
      },
    ],
  },
  {
    timestamps: true,
  }
);

// Indexes
rmaMessageSchema.index({ rmaRequest: 1, createdAt: 1 });
rmaMessageSchema.index({ 'sender.user': 1 });
rmaMessageSchema.index({ isInternal: 1 });

// Static method to get conversation for an RMA
rmaMessageSchema.statics.getConversation = function (rmaRequestId, includeInternal = false) {
  const query = { rmaRequest: rmaRequestId };
  if (!includeInternal) {
    query.isInternal = false;
  }

  return this.find(query)
    .populate('sender.user', 'email profile.firstName profile.lastName')
    .sort({ createdAt: 1 });
};

// Static method to create system message
rmaMessageSchema.statics.createSystemMessage = function (rmaRequestId, message) {
  return this.create({
    rmaRequest: rmaRequestId,
    sender: {
      type: 'system',
      name: 'System',
    },
    message,
    isAutoGenerated: true,
  });
};

// Method to mark as read
rmaMessageSchema.methods.markAsRead = async function (userId) {
  const alreadyRead = this.readBy.some(
    (r) => r.user.toString() === userId.toString()
  );

  if (!alreadyRead) {
    this.readBy.push({ user: userId, readAt: new Date() });
    await this.save();
  }

  return this;
};

// Static method to get unread count for a user
rmaMessageSchema.statics.getUnreadCount = async function (rmaRequestId, userId) {
  const count = await this.countDocuments({
    rmaRequest: rmaRequestId,
    'readBy.user': { $ne: userId },
    isInternal: false,
  });
  return count;
};

module.exports = mongoose.model('RMAMessage', rmaMessageSchema);
